name: Renovate

on:
    schedule:
        - cron: "0 5,17 * * *"
    workflow_dispatch: {}

permissions:
    contents: read
    packages: read

jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Generate GitHub App token
              id: app-token
              uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
              with:
                  client-id: ${{ vars.RENOVATE_CLIENT_ID }}
                  private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
                  owner: ${{ github.repository_owner }}
                  repositories: tolo-web

            - name: Self-hosted Renovate
              uses: renovatebot/github-action@5402b206248e5a8c8427a15102702eb9c1793efc # v46.2.4
              with:
                  token: ${{ steps.app-token.outputs.token }}
                  configurationFile: .github/renovate/config.js
              env:
                  LOG_LEVEL: info
                  RENOVATE_PLATFORM_COMMIT: "enabled"
                  RENOVATE_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
